#!/data/data/com.termux/files/usr/bin/bash
# Auto install nekopoi :v
# coded by Mr.Keep Smile
# kjhon8763@gmail.com

# Bersihkan Layar
clear

# Isi ne cuk :v
echo "    -----------My Team :---------- "
echo "    ___   ___   ___    ____ ____  "
echo "   / __//    \ /    \ /   //    \  "
echo "  / _/ /   / //   / // / //   / /  "
echo " /___//_ /\_\/_ /\_\/___//_ /\_\   "
echo "    ___ __  __ __    _____ ____    "
echo "   / __/\ \/ // /_  / _  //    \    "
echo "  / /_   \/ // __ // ___//   / /    "
echo " /___/   /_//____//____//_ /\_\     "
echo " --created by : Mr.Keep Smile-- "
echo " "
echo " "
echo " macam macam Tools termux dalam satu Tools :) "
echo " Ayo tinggal dipilih sesuai selera mastah ku :D "
echo ""
echo " 01. wpscan"
echo " 02. webdav"
echo " 03. ubuntu"
echo " 04. Red Hawk"
echo " 05. weeman"
echo " 06. D-tech"
echo " 07. Metasploit"
echo " 08. SQL lokmed"
echo " 09. hunner"
echo " 10. Youtube Dl"
echo " 11. viSQL "
echo " 12. Lazy sqlmap"
echo " 13. WfDroid"
echo " 14. FbBrute"
echo " 15. Ngrok"
echo " 16. kali nethunter"
echo " 17. Hash Buster"
echo " 18. Wifiphisher (install ubuntu terlebih dahulu) "
echo " 19. inurbl "
echo " 20. GSH-Toolbox "
echo " 21. admin page finder "
echo " 22. Gak jadi dah ah Gak punya kuota :p "
read eue

if [ $eue = 4 ] || [ $eue = 04 ]
then
clear
echo " Installing Red Hawk "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Tuhinshubhra/RED_HAWK
echo " Red Hawk nya udah ke install tuh mastah Ku :* "
fi

if [ $eue = 6 ] || [ $eue = 06 ]
then
clear
echo " Installing D-Tect "
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt-get install python2
git clone https://github.com/shawarkhanethicalhacker/D-TECT
echo " D-tect nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 9 ] || [ $eue = 09  ]
then
clear
echo " Installing Hunner "
sleep 1
apt-get update && apt-get upgrade
apt install python
apt install git
git clone https://github.com/b3-v3r/Hunner
echo " Hunner nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 1 ] || [ $eue = 01 ]
then
clear
echo " Installing Wpscan "
sleep 1
apt-get update && apt-get upgrade
apt install ruby
apt install curl
apt install git
git clone https://github.com/wpscanteam/wpscan
cd ~/wpscan
gem install bundle
bundle config build.nokogiri --use-system-libraries
bundle install
ruby wpscan.rb --update
cd ~/
echo " wpscan nya udah ke install tuh mastah ku :*  "
fi

if [ $eue = 12 ] || [ $eue = 12  ]
then
clear
echo " Installing Lazy Sqlmap "
sleep 1
apt update && apt upgrade
apt install python2
git clone https://github.com/verluchie/termux-lazysqlmap
cd ~/termux-lazysqlmap
chmod 777 install.sh
sh install.sh
cd ~/
echo " lazysqlmap nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 2 ] || [ $eue = 02 ]
then
clear
echo " Installing Webdav "
sleep 1
apt update && apt upgrade
apt install python2
pip2 install urllib3 chardet certifi idna requests
apt install openssl curl
pkg install libcurl
mkdir webdav
cd ~/webdav
wget https://pastebin.com/raw/HnVyQPtR -O webdav.py
chmod 777 webdav.py
cd ~/
echo " webdav nya nya udah ke install tuh mastah ku :*  "
fi

if [ $eue = 7 ] || [ $eue = 07 ]
then
clear
echo " Installing Metasploit "
sleep 1
apt update && apt upgrade
apt install git
apt install wget
wget https://raw.githubusercontent.com/verluchie/termux-metasploit/master/install.sh
chmod 777 install.sh
sh install.sh
echo " Metasploit nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 16 ] || [ $eue = 16 ]
then
clear
echo " Installing Nethunter "
apt update && apt upgrade
apt install git
git clone https://github.com/Hax4us/Nethunter-In-Termux.git
cd ~/Nethunter-In-Termux
chmod 777 kalinethunter
sh kalinethunter
echo " Nethunter nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 03 ] || [ $eue = 3 ]
then
clear
echo " Installing Ubuntu "
apt update && apt upgrade
apt install git
apt install wget
apt install proot
git clone https://github.com/Neo-Oli/termux-ubuntu.git
cd ~/termux-ubuntu
chmod +x ubuntu.sh
sh ubuntu.sh
echo " Fix network please wait "
sleep 1
echo "nameserver 8.8.8.8" > /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs/etc/resolv.conf
echo " Ubuntu nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 10 ] || [ $eue = 10 ]
then
clear
echo " Installing mpsyt "
apt update && apt upgrade
apt install python
pip3 install mps_youtube
pip3 install youtube_dl
apt install mpv
echo " Untuk menjalankannya ketik "mpsyt" tanpa tanda petik "
echo " Mps Youtube nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 11 ] || [ $eue = 11 ]
then
clear
echo " Installing viSQL "
apt update && apt upgrade
pkg install git
pkg install python2
git clone https://github.com/blackvkng/viSQL.git
cd ~/viSQL
chmod 777 viSQL.py
cd ~/
echo " viSQL nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 5 ] || [ $eue = 05 ]
then
clear
echo " Installing weeman "
apt update && apt upgrade
pkg install git
apt install python2
git clone https://github.com/samyoyo/weeman
cd ~/weeman
pip2 install beautifulsoup
pip2 install bs4
cd ~/
echo " Weeman nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 13 ] || [ $eue = 13 ]
then
clear
echo " Installing wfdroid "
apt update && apt upgrade
apt install wget
mkdir wfdroid
cd ~/wfdroid
wget https://raw.githubusercontent.com/bytezcrew/wfdroid-termux/master/wfdinstall
chmod 777 wfdinstall
sh wfdinstall
cd ~/
echo " WfDroid nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 14 ] || [ $eue = 14 ]
then
clear
echo " Installing Fbbrute "
apt install python2
apt install python2-dev
apt install wget
pip2 install mechanize
mkdir fbbrute
cd ~/fbbrute
wget https://pastebin.com/raw/aqMBt2xA -O fbbrute.py
chmod 777 fbbrute.py
cd ~/
echo " fbbrute nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 15 ] || [ $eue = 15 ]
then
clear
echo " Installing ngrok "
apt install wget
mkdir ngrok
cd ~/ngrok
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
cd ~/
echo " Ngrok nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 8 ] || [ $eue = 08  ]
then
clear
echo " Installing Lokmed "
apt update && apt upgrade
apt install wget
apt install php
mkdir lokmed
cd ~/lokmed
wget https://pastebin.com/raw/sPpJRjCZ -O lokmed.php
chmod 777 lokmed.php
cd ~/
echo " Lokmed nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 17 ] || [ $eue = 17  ]
then
clear
echo " Installing hashbuster "
apt update && apt upgrade
apt install python2
apt install git
git clone https://github.com/UltimateHackers/Hash-Buster
echo " hash buster nya udah ke install tuh mastah ku :* "
fi

if [ $eue = 18 ] || [ $eue = 18  ]
then
clear
echo " Installing wifiphisher "
./startubuntu.sh
apt-get install git
apt-get install python python-pip python-setuptools
pip install scapy
git clone https://github.com/wifiphisher/wifiphisher.git
cd wifiphisher
python setup.py install
echo ""
echo " wifiphisher nya udah ke install tuh mastah ku :* "
echo " untuk menjalan kan nya masukan command "
echo " cd wifiphisher "
echo " python bin/wifiphisher "
fi

if [ $eue = 19 ] || [ $eue = 19  ]
then
clear
echo " Installing inurlb "
apt update && apt upgrade
apt install git php curl
git clone https://github.com/googleinurl/SCANNER-INURLBR/ inurlbr/
cd inurlbr
chmod +x inurlbr.php
echo ""
echo " scanner inurlbr udah ke install tuh mastah ku :* "
echo " cara menjalankan nya masukan comand "
echo " php inurlbr.php -h "
echo " php inurlbr.php –help "
fi

if [ $eue = 20 ] || [ $eue = 20  ]
then
clear
echo " Installing GSHtoolbox "
apt update && apt upgrade
apt install bash
apt install git
git clone https://github.com/Yoshieichiro01/GSH-ToolBox-V.1.git
chmod 777 setup.sh
chmod 777 gshtool.sh
echo ""
echo " GSHtoolbox udah ke install tuh mastah ku :* "
echo " cara menjalankan nya masukan command "
echo " cd "
echo " cd GSH-ToolBox-V.1 "
echo " bash gshtool.sh "
fi

if [ $eue = 21 ] || [ $eue = 21  ]
then
clear
echo " Installing Ic-tool "
apt-get update&&apt-get upgrade -y
apt-get install git
pkg install python2
git clone https://github.com/mrhidden13/IC-TOOL.git
echo " Admin page finder udah keinstall tuh mastah ku :* "
echo ""
echo " untuk menjalankan nya masukan comand "
echo " cd "
echo " cd IC-TOOL "
echo " python2 ictool.py "
fi

if [ $eue = 22 ] || [ $eue = 22  ]
then
clear
echo " gapunya kuota ya ?? punya(P) tidak(T) : "
read eue
fi


if [ $eue = P ] || [ $eue = P  ]
then
echo " tumben Mastah Ku Punya kuota:D "
sleep 1
fi


if [ $eue = T ] || [ $eue = T  ]
then
echo " Haha kasian , beli dong :p "
sleep 1
exit
fi

